{% set name = "pelicanplatform" %}
{% set version = "7.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/PelicanPlatform/pelican/archive/v{{ version }}.tar.gz
    sha256: f38ae96cdb80fd81e458add9bc167108a03a90e2fe7277e15742fc0ab817f2be
  - url: https://gitlab.com/cznic/mathutil/-/raw/v1.5.0/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    fn: mathutil-LICENSE

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - pelican --help
    - pelican --version
    - pelican object copy --help

about:
  home: https://github.com/PelicanPlatform/pelican
  dev_url: https://github.com/PelicanPlatform/pelican
  summary: The Pelican command line tool
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - license-files/
    - mathutil-LICENSE
  description: |
    The Pelican command line tool allows one to use a Pelican federation as
    a client and serve datasets through running a Pelican origin service.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
