schema_version: 1

context:
  name: pelicanplatform
  version: 7.19.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/PelicanPlatform/pelican/archive/v${{ version }}.tar.gz
    sha256: 90451f834da6b69402acd7914492435e68de81fb1dae4377d4505d7ff0758637
  - url: https://gitlab.com/cznic/mathutil/-/raw/v1.5.0/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: mathutil-LICENSE

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses

tests:
  - script:
      - pelican --help
      - pelican --version
      - if: unix
        then: "pelican --version | grep -q 'Version: ${{ version }}'"
      - pelican object copy --help

about:
  summary: The Pelican command line tool
  description: |
    The Pelican command line tool allows one to use a Pelican federation as
    a client and serve datasets through running a Pelican origin service.
  homepage: https://github.com/PelicanPlatform/pelican
  repository: https://github.com/PelicanPlatform/pelican
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
    - mathutil-LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
