schema_version: 1

context:
  name: pelicanplatform
  version: "7.24.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/PelicanPlatform/pelican/archive/v${{ version }}.tar.gz
    sha256: fd73d4c9193f3a25d82c696e7269d10f84f4941786e957c8dffa1562d4b605a0
  - url: https://gitlab.com/cznic/mathutil/-/raw/v1.5.0/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/refs/tags/v0.4.0/LICENSE
    sha256: 03cfaf331a260694d06227a589cdd2b5fcfab474697b72e250736696c313655a
    file_name: LICENSE-jmespath

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses

tests:
  - script:
      - pelican --help
      - pelican --version
      - if: unix
        then: "pelican --version | grep -q 'Version: ${{ version }}'"
      - pelican object copy --help

about:
  summary: The Pelican command line tool
  description: |
    The Pelican command line tool allows one to use a Pelican federation as
    a client and serve datasets through running a Pelican origin service.
  homepage: https://github.com/PelicanPlatform/pelican
  repository: https://github.com/PelicanPlatform/pelican
  license: Apache-2.0
  license_file:
    - LICENSE
    - LICENSE-jmespath
    - LICENSE-mathutil
    - license-files/

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
